### ISSUE TITLE
Sample HealthCheck API

### ISSUE THREAD

**Issue by ramaseshan** [amonapp/amon#155]
Checks are essentially commands (or scripts) that output data to STDOUT or STDERR and produce an exit status code to indicate a state. Common exit status codes used are 0 for OK, 1 for WARNING, 2 for CRITICAL, and 3 or greater to indicate UNKNOWN or CUSTOM.

Reading through this , I understand what needs to be done, but, I am quite clueless on where to place it.
A small sample in python would also help

**Comment by martinrusev** [comment]
@ramaseshan You have to put it in a place where the `amonagent` user has access. Ideally in `/etc/opt/amonagent/checks`. As for the check itself - anything that works with Nagios / Sensu will work with Amon out of the box. Example: https://www.nagios.org/downloads/nagios-plugins/

I will update the docs, understand how this can be confusing

**Comment by ramaseshan** [comment]
@martinrusev Thanks for the path.
Assuming I dont use nagios/ sensu, and I would like some very basic health checks, would that be possible.

**Comment by martinrusev** [comment]
You can find an example here https://docs.amon.cx/plugins/#health-checks for Ruby, it is something very similar for any other scripting language. 

```
#!/usr/bin/env ruby

# get the current list of processes
processes = `ps aux`

# determine if the chef-client process is running
running = processes.lines.detect do |process|
  process.include?('mysql')
end

# return appropriate check output and exit status code
if running
  puts 'OK - Mysql process is running'
  exit 0
else
  puts 'WARNING - Mysql process is NOT running'
  exit 1
end 
```

Amon cares about 2 things;
 - The message `OK - Mysql process is running` (status - message)
 - The exit code `exit 1`, `exit 0`, etc 

Hope that was helpful !

**Comment by ramaseshan** [comment]
2 things:
1. Quite sorry, I didnt realize I was raising this issue again the amon server instead of amonagent.
2. The code sample that you had given , works quite great. I suppose we can close this issue
