### ISSUE TITLE
Agent installer could use 32bit awareness

### ISSUE THREAD

**Issue by docdawning** [amonapp/amon#170]
Howdy, I just installed the amon agent on one of my machines; a 32bit Ubuntu 16.04 web server. When I run the agent, I get:

`# amonagent -test`
`bash: /usr/bin/amonagent: cannot execute binary file: Exec format error`

Seems to me amon is pretty much a cool Django app, so I'm not sure why my 32bitness is even coming up. If it turns out 32bit support is a real chore, then I suggest the agent installer loudly tell the user they're screwed when it comes to using amon.

**Comment by djsakisd** [comment]
Hi @docdawning there is also another file inside  /usr/bin/amonagent , the  /usr/bin/amonagent32 why dont you give it a try it might work

**Comment by martinrusev** [comment]
@docdawning the agent supports 32bit. I compile one binary for 32bit and one for ARM -
 you can download these official binaries from here: https://github.com/amonapp/amonagent/releases and just replace the one in  `/usr/bin/amonagent` .

I am going to include them in the official repository at some point, whenever I have some free time

**Comment by docdawning** [comment]
Cool. I edited the _systemd_ service for amon (`/etc/systemd/system/amonagent.service`) and changed the _ExecStart_ line to read as `ExecStart=/usr/bin/amonagent32 -pidfile /var/run/amonagent/amonagent.pid`. 

I've made this comment for others like myself that wander in to this.

**Comment by docdawning** [comment]
Considering my patch for this has sat in limbo for a month, I wonder if the amon project is alive? Probably is, just seems like it's been a while. Folks are probably just busy with other things?

**Comment by martinrusev** [comment]
@docdawning It is hanging in there. I want to get back in to it, but have to deal with pretty intense deadlines on my regular job.
