### ISSUE TITLE
Sensu plugins doesn't seem to work

### ISSUE THREAD

**Issue by PabloCastellano** [amonapp/amon#174]
Hi,

I'm trying sensu plugins. Installation was fine and I can do things like

```
root@www1:/etc/opt/amonagent/plugins-enabled# check-http.rb -u https://github.com
CheckHttp OK: 200, 97807 bytes
```

However the sensu plugin configuration in Amon doesn't seem to work. I can see the plugin is activated but when I click on the button with label `Plugins.sensu.CheckHttp`, I get "No data for the selected period". Also when testing the plugin, I don't get the same output as when running the command.

```
root@www1:/etc/opt/amonagent/plugins-enabled# cat sensu.conf 
["check-http.rb -u https://github.com"]

root@www1:/etc/opt/amonagent/plugins-enabled# /opt/amonagent/amonagent -test-plugin=sensu
map[]

Executed in 770.619013ms
```

Is that `map[]` output expected?

**Comment by martinrusev** [comment]
@PabloCastellano The amonagent needs the full path to the ruby file, which should be something like `/etc/sensu/plugins/check-http.rb` 

Once this is working, you need to do the following `chown amonagent:amonagent /etc/sensu/plugins/check-http.rb`, because the agent run as user `amonagent`

**Comment by PabloCastellano** [comment]
Hi Martin.

Still doesn't work.

```
# which check-http.rb 
/usr/local/bin/check-http.rb
# cat /etc/opt/amonagent/plugins-enabled/sensu.conf                                                                                                            
["/usr/local/bin/check-http.rb -u https://github.com"]
# ls -l /usr/local/bin/check-http.rb
-rwxr-xr-x 1 amonagent amonagent 535 May 28 22:17 /usr/local/bin/check-http.rb

# /opt/amonagent/amonagent -test-plugin=sensu
map[]

Executed in 656.702372ms
```

**Comment by martinrusev** [comment]
@PabloCastellano The problem is that this one is a check plugin, which goes here:
- https://docs.amon.cx/plugins/#sensu-checks

 Example from `/etc/opt/amonagent/plugins-enabled/checks.conf` (from my local machine): 

```
[
	"check-dns.rb -d amon.cx",
	"check-disk-usage.rb -w 80 -c 90",
	"check-whois-domain-expiration.rb -d amon.cx",
	"check-ports.rb",
	"check-postgres-alive.rb",
	"check-http.rb -u https://www.amon.cx",
	"check-https-cert.rb -u https://www.amon.cx",
	"/usr/lib/nagios/plugins/check_apt",
]
```

The Sensu plugin (https://docs.amon.cx/plugins/#sensu) is only for collecting metrics . 
Example from `/etc/opt/amonagent/plugins-enabled/sensu.conf` on my local machine: 
```
[
    "metrics-dns.rb -d google.com",
    "metrics-processes-threads-count.rb -t",
]
```

**Comment by PabloCastellano** [comment]
Ooh, my mistake. Thanks for your help!
