### ISSUE TITLE
Static files not found!

### ISSUE THREAD

**Issue by RaminNietzsche** [amonapp/amon#178]
I installed Amon and I can't access to "static files", I tried it on subdomain and IP but it didn't work!

`<script src="/static/js/libs/libs.min.js"></script>`

result:

> Request Method: | GET
> http://xxx.zzzz.yyy:8000/static/images/favicon.png
> 'js/libs/libs.min.js' could not be found

**Comment by martinrusev** [comment]
@RaminNietzsche On port 8000, you can find only the Gunicorn server, which serves the Django app. For the static files, you need an nginx frontend: https://docs.amon.cx/onpremise/#proxying-with-nginx
