### ISSUE TITLE
remote engine question

### ISSUE THREAD

**Issue by djsakisd** [amonapp/amon#180]
@martinrusev  Hi Martin

I was wondering what happened with the remote engine for amon  you introduced at some point ?

**Comment by martinrusev** [comment]
@djsakisd it is coming up in another product called infrabeam. Believe in the idea that your monitoring tool should be able to do some of the maintenance for you automatically. In this case the remote engine was super useful, but Amon started getting too complicated

**Comment by djsakisd** [comment]
@martinrusev  you have a point in complication but stil its a very usefull feature to have a "console" right in the webui for the monitoring systems, at least you can inspect without using the console at all, just my opinion.
BTW do you have any plans to support users with permisions on amon and any ETA on the infrabeam product and pricing ?

**Comment by martinrusev** [comment]
@djsakisd It is my opinion as well. I like that option very much and I believe there is a huge niche to be filled. We have a lot of tools for initial setup(terraform, ansible, etc), but not many options for maintenance. For Amon - I am looking into user permissions and also LDAP support. For infrabeam - I want to release it by the end of the year. Have a functional product that works well for my own use, needs more polish before release

**Comment by djsakisd** [comment]
@martinrusev thanks for all the info.
Really looking forward for user permissions and infrabeam. 
Keep up the great  work you are doing with amon.

I'm closing the issue.
