### ISSUE TITLE
Emails are not sending

### ISSUE THREAD

**Issue by knokio** [amonapp/amon#181]
Everything is configured accordingly but the alert emails are not sending. 
I double checked the amon.yml configuration and the logs but can't find anything.

Is there a simple way to test/validate the email sending?

**Comment by martinrusev** [comment]
@knokio the email sending and notifications in general go through a cron job. 'crontab -l' as user 'amon' schould show the current status. 2 ways to see if it is working:
- cat /var/log/amon/amonapp.log
- using a local smtp service like Mailhog to see if emails are going through.

**Comment by knokio** [comment]
This is all it has on that log.

`root@1b3be77f6f50:/opt/amon# tail -f -n2000 /var/log/amon/amonapp.log
[27/Sep/2017 10:13:19] WARNING [django.request:152] Not Found: /favicon.ico
[27/Sep/2017 10:13:19] WARNING [django.request:152] Not Found: /favicon.ico
`

I tried to send a test email and it worked "Settings > Notifications > Email > Test".
Also, the Slack notifications don't work but the test does. 🤔 

Any more ideas?

**Comment by knokio** [comment]
Continuing the investigation: everything is in cron (3 tasks).

I tried to run the first manually and the emails started going out: `/usr/bin/python3 /opt/amon/manage.py runtask send_notifications_task  --settings=amon.settings`

**Comment by martinrusev** [comment]
@knokio looks like some sort of a permission issue. Can you check if the cron jobs are for the root user or for amon?

**Comment by knokio** [comment]
@martinrusev the cron are defined in the root crontab
