### ISSUE TITLE
Failed tests

### ISSUE THREAD

**Issue by vladimirkolev** [amonapp/amon#189]
https://github.com/amonapp/amon/blob/ce8f0adce0476b8ce0436b09bf6fb19932252dd1/amon/apps/plugins/helpers.py#L64

Wouldn't be better:

```python

def remove_dots(obj):
    new_obj = {}
    for key, value in obj.items():
        new_obj[key.replace("_", ".")] = value
    return new_obj
```
The other method, although elegant, sometimes brakes the order of the dictionary, so the test fails

**Comment by martinrusev** [comment]
Fixed in https://github.com/amonapp/amon/commit/27f56ee70992b66c58ed160d2a4b977e048967ea
