### ISSUE TITLE
Bash health check returning "UNKNOWN" status

### ISSUE THREAD

**Issue by jamestombs** [amonapp/amon#192]
I created a health check using bash, bash script is:

```
#!/bin/bash
SERVICE=$1
if ps ax | grep -v grep | grep $SERVICE > /dev/null
then
    echo "$SERVICE service running"
    exit 0
else
    echo "$SERVICE is not running"
    exit 1
fi
```
Then in `/etc/opt/amonagent/plugins-enabled/checks.conf` I have:

`["bash /root/adapt_running.sh adapt"]`

Running that command from command line I get:

```
# bash ./adapt_running.sh adapt
adapt service running
```

Running through amonagent I get:

```
# amonagent -test-plugin=checks
[{"name":"","command":"bash /root/adapt_running.sh adapt","exit_code":0,"output":"adapt service running\n","error":""}]
```

Amon server always shows an UNKNOWN state, last check always states "a few seconds ago".

**Comment by nmaggioni** [comment]
I am getting the same behavior:

```json
### /etc/opt/amonagent/plugins-enabled/checks.conf
["bash check_rancher.sh", "bash check_proxmox.sh"]
```

```bash
### /etc/opt/amonagent/plugins-enabled/check_proxmox.sh
#!/bin/bash
if nc -zw5 127.0.0.1 8006; then
	echo "Proxmox is reachable"
	exit 1
else
	echo "Proxmox is unreachable"
	exit 2
fi
```

`check_rancher.sh` is the same as above, only the port number changes. Both scripts make checks statuses show up as "UNKNOWN" in Amon.

---

Moreover, since I translated my checks into Python, Amon now shows them failing with "CRITICAL" status - despite running `amonagent -test-plugin=checks` locally confirms that both scripts exit with `0` code.

```python
### /etc/opt/amonagent/plugins-enabled/check_proxmox.py
#!/usr/bin/env python3

import socket

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.settimeout(5)
result = sock.connect_ex(('127.0.0.1', 8006))
if result == 0:
    print("Proxmox is reachable")
    quit(0)
else:
    print("Proxmox is unreachable")
    quit(1)
```

```json
$ amonagent -test-plugin=checks
[{"name":"","command":"python3 check_proxmox.py","exit_code":0,"output":"Proxmox is reachable\n","error":""} {"name":"","command":"python3 check_rancher.py","exit_code":0,"output":"Rancher is reachable\n","error":""}]
```

**Comment by martinrusev** [comment]
@nmaggioni, @jamestombs Looking into it

**Comment by martinrusev** [comment]
@jamestombs  Just did the following
1. copy pasted your bash script and saved it to `/usr/local/bin/service-check.sh`
1.  `chmod +x /usr/local/bin/service-check.sh` 
1. In `/etc/opt/amonagent/plugins-enabled` added ` "/usr/local/bin/service-check.sh amonagent"`

And got the results 
![checks](https://user-images.githubusercontent.com/103003/33385333-9b85d81a-d528-11e7-9e24-0e2279cbfc63.jpg)

The issue most probably is as following, when running `amonagent -test` in the terminal, it is done through the currently logged in user, usually `root`. The agent on the other side runs as `amonagent` and  maybe does not have the permissions to properly execute the bash / python scripts`

**Comment by nmaggioni** [comment]
@martinrusev In my case running `sudo -u amonagent amonagent -test-plugin=checks` yields the same result (now using both Bash and Python checks, doing the same thing):

```json
[{"name":"","command":"bash check_proxmox.sh","exit_code":0,"output":"Proxmox is reachable\n","error":""} {"name":"","command":"bash check_rancher.sh","exit_code":0,"output":"Rancher is reachable\n","error":""} {"name":"","command":"python3 check_proxmox.py","exit_code":0,"output":"Proxmox is reachable\n","error":""} {"name":"","command":"python3 check_rancher.py","exit_code":0,"output":"Rancher is reachable\n","error":""}]
```

Bash checks are still marked as **Unknown**, and Python ones as **Critical**:

![screenshot](https://user-images.githubusercontent.com/3594528/33385858-eb02ec92-d529-11e7-94e8-c2694440742b.png)

**Comment by martinrusev** [comment]
@nmaggioni What we need is the checks executed by the `amonagent` user:

```
sudo -u amonagent -s
whoami
amonagent -test-plugin=checks
```

**Comment by nmaggioni** [comment]
@martinrusev You are right, I didn't fully change user to `amonagent`:

```json
[{"name":"","command":"bash check_proxmox.sh","exit_code":126,"output":"","error":""} {"name":"","command":"bash check_rancher.sh","exit_code":126,"output":"","error":""} {"name":"","command":"python3 check_rancher.py","exit_code":2,"output":"","error":""} {"name":"","command":"python3 check_proxmox.py","exit_code":2,"output":"","error":""}]
```
---

Turns out that the full path needs to be specified in `checks.conf`!

```json
# checks.conf
["bash /etc/opt/amonagent/plugins-enabled/check_rancher.sh", "python3 /etc/opt/amonagent/plugins-enabled/check_rancher.py", "bash /etc/opt/amonagent/plugins-enabled/check_proxmox.sh", "python3 /etc/opt/amonagent/plugins-enabled/check_proxmox.py"]
```
```json
# Running checks as the `amonagent` user
[{"name":"","command":"bash /etc/opt/amonagent/plugins-enabled/check_proxmox.sh","exit_code":0,"output":"Proxmox is reachable\n","error":""} {"name":"","command":"bash /etc/opt/amonagent/plugins-enabled/check_rancher.sh","exit_code":0,"output":"Rancher is reachable\n","error":""} {"name":"","command":"python3 /etc/opt/amonagent/plugins-enabled/check_rancher.py","exit_code":0,"output":"Rancher is reachable\n","error":""} {"name":"","command":"python3 /etc/opt/amonagent/plugins-enabled/check_proxmox.py","exit_code":0,"output":"Proxmox is reachable\n","error":""}]
```

![screenshot](https://user-images.githubusercontent.com/3594528/33389865-78741a74-d534-11e7-8520-c8c5de249569.png)

Will old checks go away by themselves when the retention cycle triggers?

Thanks for the help! :smile:

**Comment by martinrusev** [comment]
@nmaggioni Super. The old checks will cleanup eventually, but currently the retention cycle is 1 month. This is on my `very soon` list of priorities. Will enable a setting to customize retention for checks + will add a delete button in the health checks page

**Comment by nmaggioni** [comment]
Great news! Keep up the good work :+1:

Is the issue solved for @jamestombs too?

**Comment by jamestombs** [comment]
Yes, I moved the bash script out of /root so that the amonagent user could have access and we have success. This may well be linked to my other issue with a plugin not working.
