### ISSUE TITLE
Agent daemon not running after restart

### ISSUE THREAD

**Issue by maxklock** [amonapp/amon#215]
After downloading and installing the Agent, everthing works fine. The Server is receiving the metrics every Minute. But after rebooting the Client Server, the Agent is not running and can not be started as a Service. I've to start the Agent myself as a Background command (screen => amonagent):

    amonagent.service - Starts and stops amonagent
        Loaded: loaded (/lib/systemd/system/amonagent.service; enabled; vendor preset: enabled)
        Active: failed (Result: exit-code) since Thu 2018-08-23 22:10:42 CEST; 3min 25s ago
        Docs: https://www.amon.cx/docs
        Process: 6136 ExecStart=/usr/bin/amonagent -pidfile /var/run/amonagent/amonagent.pid (code=exited, status=1/FAILURE)
        Main PID: 6136 (code=exited, status=1/FAILURE)

    Aug 23 22:10:42 Max-Klock systemd[1]: amonagent.service: Main process exited, code=exited, status=1/FAILURE
    Aug 23 22:10:42 Max-Klock systemd[1]: amonagent.service: Failed with result 'exit-code'.
    Aug 23 22:10:42 Max-Klock systemd[1]: amonagent.service: Service hold-off time over, scheduling restart.
    Aug 23 22:10:42 Max-Klock systemd[1]: amonagent.service: Scheduled restart job, restart counter is at 5.
    Aug 23 22:10:42 Max-Klock systemd[1]: Stopped Starts and stops amonagent.
    Aug 23 22:10:42 Max-Klock systemd[1]: amonagent.service: Start request repeated too quickly.
    Aug 23 22:10:42 Max-Klock systemd[1]: amonagent.service: Failed with result 'exit-code'.
    Aug 23 22:10:42 Max-Klock systemd[1]: Failed to start Starts and stops amonagent.

**Comment by rpirsc13** [comment]
User amonagent does not have access to write to /var/run/amonagent for the pid file

Fix 1:
`sudo touch /etc/default/amonagent`
Edit amonagent.service and add following under [Service]
`EnvironmentFile=-/etc/default/amonagent`

Fix 2:
Edit amonagent.service and add following under [Service]
```
PermissionsStartOnly=true
ExecStartPre=-/usr/bin/mkdir /var/run/amonagent
ExecStartPre=/usr/bin/chown -R amonagent:amonagent /var/run/amonagent/
```
